name: Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "30 8 * * *"
  push: # for test

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download Exclude Path
        run: |
          curl https://raw.githubusercontent.com/aFlyBird0/devstream-fork/main/.lycheeignore --output .lycheeignore
      - name: Check Links
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          # For parameter description, see https://github.com/lycheeverse/lychee#commandline-parameters
          # -E, --exclude-mail           Exclude all mail addresses from checking
          # -v, --verbose                Verbose program output
          # -i, --insecure               Proceed for server connections considered insecure (invalid TLS)
          # -n, --no-progress            Do not show progress bar.
          # -t, --timeout <timeout>      Website timeout in seconds from connect to response finished [default:20]
          args: -E --exclude-mail -v -i -n -t 45 -- **/*.md
          output: out.md
        env:
          GITHUB_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}

      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Broken Link Detected
          content-filepath: out.md
          assignees: aFlyBird0
